stages:
  - test
  - build
  - deploy

# ONLY Build when front(FrontendCarProject) in changed
build_front:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm test
    - npm start
  artifacts:
    paths:
      - ./dist

# ONLY build when backend(BackendCarProject) is changed
build_back:
  stage: build
  image: openjdk:17-alpine
  script:
    - .gradle bootRun
  artifacts:
    paths:
      - ./build/libs/