stages:
  - test
  - build
  - deploy

# ONLY Build when front(FrontendCarProject) in changed
build_front:
  stage: build
  image: node:latest
  script:
    - cd Frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./Frontend/dist

# ONLY build when backend(BackendCarProject) is changed
build_back:
  stage: build
  image: openjdk:17-alpine
  script:
    - cd Backend
    - ./gradlew bootRun
  artifacts:
    paths:
      - ./Backend/build/libs/
