stages:
  - test
  - build
  - deploy

build_front:
  stage: build
  image: node:latest
  script:
    - cd Frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./Frontend/dist

build_back:
  image: gradle:alpine
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle


